### PR TITLE
Code overhaul/cleanup

### PR DESCRIPTION
**Pull request by BitByLogics**
- Downsize classes
- Overhaul config.yml
- Take advantage of BlockDropItemEvent for drop logic
- Allow configuration of drops to remove
- Add /dropsoverhaul command
- Add /dropsoverhaul reload to reload configuration
- Rename /killdrops to /dropsoverhaul killdrops
- Allow messages to be configured in config.yml
- Remove default-everyone-killdrops option, permission can just be negated
- Add BitByLogic to authors

### CODE REVIEW

**Comment by FrankTCA** [comment]
Thanks for this! Reviewing this is a lot, and I don't have time today.

I want to make sure that everything still works the way it's supposed to.

First, when I briefly looked through your code, I didn't see anything that could damage the player's tool when they use it. I can handle this code if you don't have time to do that.

I've been trying to find a way to configure block choices, so thanks for that.

I prefer to use more than one command, especially for commands that default to any player can use them. I will keep /dropsoverhaul reload, but I'd like to make /killdrops its own command,only because I prefer any commands that are sometimes run by non-operators to be standalone commands.

Similar to how Essentials does things, I will detect the presence of a permissions plugin and then ignore default-everyone-killdrops depending on the presence of a permissions plugin.

I prefer to do that because I play a lot of SMPs that I like to set up from a template in an hour. Configuring permissions can often get in the way of that, and I believe I'm probably not the only person like that.

Anyway, thanks for the complete overhaul of this plugin. I've simply been way too busy with other things to do it myself. I'll probably be able to review and merge it fully in about a week.

**Comment by BitByLogics** [comment]
All good! Also yeah, the durability is handled automatically by Spigot. The new event I use only deals with the drops of the blocks!

**Comment by FrankTCA** [comment]
Hey! Thanks so much for this massive overhaul! This has been one of my smaller projects for about four or so years now (formerly just used on my own server, GH only dates back about 2-3). If you'd like, I can make you a permanent contributor, you're also welcome to check out some of my other more popular projects, like [Lorax Custom Trees](https://github.com/FrankTCA/LoraxCustomTrees).

Looking ahead if you're willing, I also used to develop OpenTerrainGenerator, but parted ways with the original dev team because of disputes over project direction. I developed [a fork](https://github.com/FrankTCA/OpenTopG) that survived the original version of the software for about a year but I lagged behind with new vanilla world features because I was just trying to keep it running with the latest updates. Many people in the OTG community preferred my version despite the bugs (because I supported the latest release and because the OTG team planned to convert everything to YAML, which would break some 8-year-old actively developed presets). I eventually reached an impasse with Mojang code changes in 1.19.3, and unfortunately nobody in that community, although they really wanted and worked hard to help it, was smart enough to get it to the next update. (Official OTG repository has not seen a change since February of last year, and very little changes since I left in February 2022).

If I had even one more developer, I may be able to take a crack at getting that to 1.20.6 and making new game features like world height actually work like vanilla.

Anyways, that's only if you're interested, but if you'd like to help out with this project, or the Lorax, I can make you contributor. I'm quite impressed with how small you made my code. I really need to read into the Spigot API and what it supports more!

**Comment by BitByLogics** [comment]
Yeah sounds awesome! If you want you can add me as a contributor to both and I can chip in where I can. Also thanks! My forte is optimizing/minimizing code bases. I love trying to optimize and shrink things down to the bare minimum while keeping functionality and readability.

**Comment by BitByLogics** [comment]
Do you have Discord? If so, could you add me BitByLogic on Discord. It's easier to talk there👍🏻

**Comment by FrankTCA** [comment]
I don't have Discord or really any social media. I use my own platform, but I don't dox it on public places. If you send me an email at frank@infotoast.org (feel free to use an alt email or a protonmail account because I just need you to send me an email so I can return the joining info, no need to give me any private info).

Let me know if there's a better way to reach you that doesn't involve a social platform. I can also generate a self-destructing hyperlink that leads to a .txt file with the info.

P.S. It's not really difficult to set up. It doesn't require any special apps (there is an optional mobile/desktop app version) but no weird software like Tor or SSH. It works just fine in Google Chrome or any other browser.

**Pull request merged**
